# Generated by Django 5.0.6 on 2024-07-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oblApp', '0002_wall_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='wall',
            name='crew',
            field=models.IntegerField(default=0),
        ),
    ]
