# Generated by Django 5.0.6 on 2024-07-12 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oblApp', '0003_data_wall_crew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('estimate_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='wall',
            name='id',
        ),
        migrations.AddField(
            model_name='wall',
            name='wall_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=31)),
                ('middle_name', models.CharField(blank=True, max_length=31)),
                ('last_name', models.CharField(max_length=31)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('property_address', models.CharField(max_length=1000)),
                ('billing_address', models.CharField(blank=True, default=models.CharField(max_length=1000), max_length=1000)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='oblApp.estimate')),
            ],
        ),
        migrations.CreateModel(
            name='ScopeOfWork',
            fields=[
                ('scope_id', models.AutoField(primary_key=True, serialize=False)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_of_work', to='oblApp.estimate')),
            ],
        ),
        migrations.CreateModel(
            name='Insulation',
            fields=[
                ('insulation_id', models.AutoField(primary_key=True, serialize=False)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insulations', to='oblApp.scopeofwork')),
            ],
        ),
        migrations.CreateModel(
            name='SprayFoam',
            fields=[
                ('spray_foam_id', models.AutoField(primary_key=True, serialize=False)),
                ('insulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spray_foam', to='oblApp.insulation')),
            ],
        ),
        migrations.AddField(
            model_name='wall',
            name='spray_foam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wall', to='oblApp.sprayfoam'),
            preserve_default=False,
        ),
    ]
