# Generated by Django 5.0.6 on 2024-07-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oblApp', '0004_estimate_remove_wall_id_wall_wall_id_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
