# Generated by Django 5.0.6 on 2024-07-12 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oblApp', '0005_alter_client_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='estimate',
        ),
        migrations.AddField(
            model_name='estimate',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='oblApp.client'),
            preserve_default=False,
        ),
    ]
